<?php
/**
 * igov theme module
 */

/**
 * constant declaration
 */
// base image name
define('IGOV_SLIDER_IMAGE_NAME', 'slides_image-');
// slider directory
define('IGOV_SLIDER_DIRECTORY', 'igov_slides/');

// Create a block that handles the banner slider
function igov_block_info(){

  $blocks['igov_slides'] = array(
    'info' => t('GWT: Banner Image Slider'),
    'region' => 'banner',
  );
  $blocks['igov_trans_seal'] =  array(
    'info' => t('GWT: Transparency Seal'),
    'region' => 'sidebar_first',
    'visibility' => 'BLOCK_VISIBILITY_LISTED',
    'pages' => '<front>',
  );

  return $blocks;
}

function igov_block_configure($delta = '') {
  // This example comes from node.module.
  $form = array();

  switch ($delta) {
    case 'igov_slides':
      // TODO: create a basic settings for image slider
      // full width settings
      $form['test'] = array(
        //'#markup' => '<pre>'.print_r(image_styles(), 1).'</pre>',
        );
      break;
    case 'igov_trans_seal':
      $form['igov_fieldset'] = array(
        '#type' => 'fieldset',
        '#title' => t('Settings'),
      );
      $form['igov_fieldset']['trans_link'] = array(
        '#type' => 'textfield',
        '#title' => 'Image Link',
        '#description' => t('Transparency image link.').'<br/><strong>e.g.</strong> node/1 or &lt;front&gt;',
        '#default_value' => variable_get('igov_trans_seal_link', 'node'),
      );
      break;
  }
  return $form;
}

/**
 * implementation of hook_block_save()
 */
function igov_block_save($delta, $edit=array()){
  switch ($delta) {
    case 'igov_trans_seal':
      // TODO: check if link exists
      if(!drupal_valid_path($edit['trans_link'])){
        break;
      }
      variable_set('igov_trans_seal_link', $edit['trans_link']);
      break;
	}
}

/**
 * implementation of hook_block_view
 */
function igov_block_view($delta = ''){
  $block = array();

  if($delta == 'igov_trans_seal'){
    $link = variable_get('igov_trans_seal_link', 'node');

    // print the transparency seal here
    $trans_seal = path_to_theme().'/images/transparency-seal.png';
    $trans_seal = theme_image(
      array(
        'path' => $trans_seal,
        'attributes' => array(
          'alt' => 'transparency-seal',
        ),
      ));
    
    if($link != 'node'){
      $trans_seal = l($trans_seal, $link, array(
        'html' => true,
        ));
    }
    $trans_seal = '<div class="transparency-seal">'.$trans_seal.'</div>';

    $block['subject'] = t('Transparency Seal');
    $block['content'] = $trans_seal;
  }

  return $block;
}
